"""
Cell Count Analysis Script
Analyzes CSV files generated by Bio-Oracle tracking
"""
import csv
import sys
from pathlib import Path
import statistics


def analyze_cell_counts(csv_path: str):
    """
    Analyze cell count data from CSV file.
    
    Args:
        csv_path: Path to CSV file with cell count data
    """
    if not Path(csv_path).exists():
        print(f"❌ Error: File not found: {csv_path}")
        return
    
    # Read data
    data = []
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            data.append({
                'frame': int(row['frame']),
                'cell_count': int(row['cell_count']),
                'time_elapsed': float(row['time_elapsed'])
            })
    
    if not data:
        print("❌ No data found in CSV file")
        return
    
    # Extract cell counts
    cell_counts = [d['cell_count'] for d in data]
    
    # Calculate statistics
    total_frames = len(data)
    min_cells = min(cell_counts)
    max_cells = max(cell_counts)
    avg_cells = statistics.mean(cell_counts)
    median_cells = statistics.median(cell_counts)
    
    # Calculate variance and stability
    if len(cell_counts) > 1:
        stdev = statistics.stdev(cell_counts)
        variance = statistics.variance(cell_counts)
    else:
        stdev = 0
        variance = 0
    
    # Find frames with min/max cells
    min_frame = next(d['frame'] for d in data if d['cell_count'] == min_cells)
    max_frame = next(d['frame'] for d in data if d['cell_count'] == max_cells)
    
    # Calculate cell count changes
    changes = []
    for i in range(1, len(data)):
        change = data[i]['cell_count'] - data[i-1]['cell_count']
        changes.append(change)
    
    # Count increases/decreases
    increases = sum(1 for c in changes if c > 0)
    decreases = sum(1 for c in changes if c < 0)
    stable = sum(1 for c in changes if c == 0)
    
    # Print analysis
    print("\n" + "="*70)
    print("CELL COUNT ANALYSIS REPORT")
    print("="*70)
    print(f"CSV File: {csv_path}")
    print(f"Total Duration: {data[-1]['time_elapsed']:.2f} seconds")
    print()
    
    print("📊 SUMMARY STATISTICS")
    print("-" * 70)
    print(f"Total Frames Analyzed:    {total_frames}")
    print(f"Minimum Cell Count:       {min_cells} (Frame {min_frame})")
    print(f"Maximum Cell Count:       {max_cells} (Frame {max_frame})")
    print(f"Average Cell Count:       {avg_cells:.2f}")
    print(f"Median Cell Count:        {median_cells}")
    print(f"Standard Deviation:       {stdev:.2f}")
    print(f"Variance:                 {variance:.2f}")
    print()
    
    print("📈 CELL COUNT DYNAMICS")
    print("-" * 70)
    print(f"Frame-to-Frame Increases: {increases} ({increases/total_frames*100:.1f}%)")
    print(f"Frame-to-Frame Decreases: {decreases} ({decreases/total_frames*100:.1f}%)")
    print(f"Stable Frames:            {stable} ({stable/total_frames*100:.1f}%)")
    print()
    
    # Cell count distribution
    print("📉 CELL COUNT DISTRIBUTION")
    print("-" * 70)
    unique_counts = sorted(set(cell_counts))
    for count in unique_counts:
        frequency = cell_counts.count(count)
        percentage = (frequency / total_frames) * 100
        bar = "█" * int(percentage / 2)
        print(f"{count:3d} cells: {bar} {frequency:4d} frames ({percentage:5.1f}%)")
    print()
    
    # Stability assessment
    print("🔍 STABILITY ASSESSMENT")
    print("-" * 70)
    if stdev < 2:
        stability = "Very Stable"
    elif stdev < 5:
        stability = "Stable"
    elif stdev < 10:
        stability = "Moderate Variability"
    else:
        stability = "High Variability"
    
    print(f"Population Stability:     {stability}")
    print(f"Cell Count Range:         {max_cells - min_cells} cells")
    
    # Growth trend
    first_quarter = cell_counts[:len(cell_counts)//4]
    last_quarter = cell_counts[-len(cell_counts)//4:]
    avg_first = statistics.mean(first_quarter)
    avg_last = statistics.mean(last_quarter)
    
    if avg_last > avg_first + 2:
        trend = "Increasing (Growth)"
    elif avg_last < avg_first - 2:
        trend = "Decreasing (Death/Migration)"
    else:
        trend = "Stable"
    
    print(f"Overall Trend:            {trend}")
    print(f"  - First Quarter Avg:    {avg_first:.1f} cells")
    print(f"  - Last Quarter Avg:     {avg_last:.1f} cells")
    print()
    
    # Key insights
    print("💡 KEY INSIGHTS")
    print("-" * 70)
    
    if max_cells - min_cells <= 3:
        print("✓ Very consistent cell population throughout video")
    elif max_cells - min_cells <= 10:
        print("✓ Relatively stable cell population with minor fluctuations")
    else:
        print("⚠ Significant variation in cell count detected")
    
    if avg_cells < 10:
        print("ℹ Low cell density environment")
    elif avg_cells < 50:
        print("ℹ Medium cell density environment")
    else:
        print("ℹ High cell density environment")
    
    print()
    print("="*70)
    print()


def compare_videos(csv_paths: list):
    """Compare cell counts across multiple videos."""
    print("\n" + "="*70)
    print("MULTI-VIDEO COMPARISON")
    print("="*70)
    
    for csv_path in csv_paths:
        if not Path(csv_path).exists():
            print(f"⚠ Skipping missing file: {csv_path}")
            continue
        
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            data = list(reader)
            cell_counts = [int(row['cell_count']) for row in data]
            
            avg = statistics.mean(cell_counts)
            max_c = max(cell_counts)
            min_c = min(cell_counts)
            
            print(f"\n{Path(csv_path).name}:")
            print(f"  Frames: {len(data)}, Avg: {avg:.1f}, Min: {min_c}, Max: {max_c}")
    
    print("\n" + "="*70)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python analyze_cells.py <csv_file> [csv_file2 ...]")
        print("\nExample:")
        print("  python analyze_cells.py logs/cell_counts_video2_20260221_143020.csv")
        print("\nOr analyze the most recent CSV:")
        print("  python analyze_cells.py logs/*.csv")
        return
    
    csv_files = sys.argv[1:]
    
    if len(csv_files) == 1:
        # Single file analysis
        analyze_cell_counts(csv_files[0])
    else:
        # Multi-file comparison
        for csv_file in csv_files:
            analyze_cell_counts(csv_file)
        
        if len(csv_files) > 1:
            compare_videos(csv_files)


if __name__ == '__main__':
    main()
